[pytest]
markers =
    smoke: smoke tests
    regression: regression tests
    critical: critical path tests
addopts =
    --strict-markers
    --tb=short
    --alluredir=allure-results
    --clean-alluredir
    -v
    -s
    -n auto
testpaths = tests
